# Generated by Django 4.2.7 on 2023-11-16 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('health_rating', models.IntegerField(blank=True, null=True)),
                ('meat_type', models.CharField(blank=True, choices=[('beef', 'beef'), ('pork', 'pork'), ('chicken', 'chicken')], max_length=10, null=True)),
                ('size', models.CharField(blank=True, choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], max_length=2, null=True)),
                ('purchase_price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.item')),
            ],
            options={
                'abstract': False,
            },
            bases=('testapp.item',),
        ),
        migrations.CreateModel(
            name='Through',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_through', to='testapp.item')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_through', to='testapp.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='items',
            field=models.ManyToManyField(related_name='items', through='testapp.Through', to='testapp.item'),
        ),
        migrations.AddConstraint(
            model_name='through',
            constraint=models.UniqueConstraint(fields=('item', 'menu_item'), name='unique_item'),
        ),
    ]
